[package]
name = "cott-pluck"
version.workspace = true
edition = "2021"
license.workspace = true
authors.workspace = true
description = "CottPluck — dusty guitar as a nih-plug VST3"

[lib]
crate-type = ["cdylib"]

[dependencies]
cott-pluck-dsp = { workspace = true }
cott-plugin-ui = { workspace = true }
nih_plug = { workspace = true }
nih_plug_egui = { workspace = true }
