[package]
name = "cott-drums"
version.workspace = true
edition = "2021"
license.workspace = true
authors.workspace = true
description = "CottDrums — analog pad drum machine VST3"

[lib]
crate-type = ["cdylib"]

[dependencies]
cott-drums-dsp = { workspace = true }
cott-plugin-ui = { workspace = true }
nih_plug = { workspace = true }
nih_plug_egui = { workspace = true }
